### ISSUE TITLE
Rotary encoder goes wrong direction

### ISSUE THREAD

**Issue by stefi01** [Edzelf/ESP32Radio-V2#102]
How do I change the direction of the encoder, volume up (clockwise) makes the volume go down and anticlockwise volume up

**Comment by Edzelf** [comment]
Simply reverse the 2 signals (usually clk and dt).  You can do this by resoldering the wires to the switch or to swap the pin definitions in the config page of the webinterface, for example:
```
pin_enc_clk = 25     # GPIO rotary encoder CLK
pin_enc_dt = 26      # GPIO rotary encoder DT

```
to
```
pin_enc_clk = 26     # GPIO rotary encoder CLK
pin_enc_dt = 25      # GPIO rotary encoder DT
```
