### ISSUE TITLE
Need Help!!!

### ISSUE THREAD

**Issue by buddyroar** [Edzelf/ESP32Radio-V2#106]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 115200, None, Disabled"

C:\Users\Buddy\Documents\Arduino\libraries\utils\utils.cpp:29:6: error: ambiguating new declaration of 'void dbgprint(const char*, ...)'

 void dbgprint ( const char* format, ... )

      ^~~~~~~~

In file included from C:\Users\Buddy\Documents\Arduino\libraries\utils\utils.cpp:5:

C:\Users\Buddy\Documents\Arduino\libraries\utils\utils.h:11:13: note: old declaration 'char* dbgprint(const char*, ...)'

 char*       dbgprint ( const char* format, ... ) ;                 // Print a formatted debug line

             ^~~~~~~~

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\Buddy\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.6\libraries\WiFi

 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries\WiFi

exit status 1

Error compiling for board DOIT ESP32 DEVKIT V1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Edzelf** [comment]
Looks like you have mixed versions.  Please load the complete zip-file, upload sketch and data dairectory.

**Comment by buddyroar** [comment]
Could you explain what you mean by mixed versions?

**Comment by Edzelf** [comment]
Sorry, my fault.  Just a moment.

**Comment by Edzelf** [comment]
Correct version is now available.

**Comment by buddyroar** [comment]
Thank you, I will try to upload the new version once I’m home tonight.
