### ISSUE TITLE
i2c LCD2004 display not displaying title or radio station

### ISSUE THREAD

**Issue by timo619** [Edzelf/ESP32Radio-V2#42]
Hi, 

I have connected a LCD2004 display to my ESP-wroom-32 with an encoder. Audio via i2s `#define DEC_HELIX `.

The display only shows date and time. When I press the encoder (singleclick) it says Mute in the 2nd line. 
When I doubleclick it shows the station and after 2 seconds  the text "Turn to select station Press to confirm".
The preset is not shown when I turn the encoder. Also the Mute is not going away when I unmute. Volume bar is also not shown when turning the encoder. 
![photo_2022-05-12_20-29-26](https://user-images.githubusercontent.com/94706943/168144137-18f19ebb-1e59-45c5-a6fe-bd7e3327cfe6.jpg)
![photo_2022-05-12_20-29-29](https://user-images.githubusercontent.com/94706943/168144143-c41fc2f5-d0a5-4200-a693-3d2f555cc207.jpg)
![photo_2022-05-12_20-29-31](https://user-images.githubusercontent.com/94706943/168144146-afaabaa1-3ce0-4579-b999-ba337041b046.jpg)

Do you have any tips for me where to search the problem in the source code?

**Comment by Edzelf** [comment]
Please try today's version.  I have tested it, although without the encoder.

**Comment by timo619** [comment]
Thank you very much. Great work. It is working now as expected. See picture below:
![photo_2022-05-12_21-16-18](https://user-images.githubusercontent.com/94706943/168151558-8b7abe3b-b41e-4c2a-a467-f5176277a177.jpg)
