### ISSUE TITLE
Unable to connect WiFi 

### ISSUE THREAD

**Issue by dkotte** [Edzelf/ESP32Radio-V2#45]
i am unable to connect wifi.
Config is nearly empty. Only 2 Wifi networks with correct Password ( i try only numbers)
`
D: Create list with acceptable WiFi networks

D: Added MYWIFI to list of networks
D: Added STV to list of networks
D: Added SGuest to list of networks
D: Scan Networks
D: Scan completed
D: Number of available networks: 11
D:  1 - SGuest                  Signal: -73 dBm, Encryption WPA2_PSK, Acceptable
D:  2 - STV                       Signal: -74 dBm, Encryption WPA2_PSK, Acceptable
D:  3 - ....
...
D: Connect to network
D: WiFi Failed!  Trying to setup AP with name ESP32-Radio and password ESP32-Radio.
D: IP = 1.0.0.0
D: Start web server
`
What can i do or try?

**Comment by Edzelf** [comment]
Try to specify one network in config.h instead of MYWIFI.

**Comment by dkotte** [comment]
Thanks for the hint ... very useful to predefine one wifi...
.. But the problem is configured local ... mot an esp32radio-problem.
Thanks!

**Comment by dkotte** [comment]
Thanks.
