### ISSUE TITLE
esp32radio v2 with 2 esp32!!!

### ISSUE THREAD

**Issue by clear-sky** [Edzelf/ESP32Radio-V2#85]
As far as I understand, due to technical problems, the Bluetooth transmitter cannot be integrated with the radio, so why not use two esp32? In this case, both the project will be more intimate and its educational aspect will be higher!!!

**Comment by Edzelf** [comment]
Agree. Just connect a Bluetooth transmitter to the audio output.

**Comment by WerkAG** [comment]
Here is an example using a  Bluetooth transmitter...<br><br>

![IMG_20221113_050903_479](https://user-images.githubusercontent.com/14356332/201507650-d6aeef9c-f1ef-495b-8586-b36859739626.jpg)

**Comment by clear-sky** [comment]
hi all 
i mean using an esp32 as radio reciever via wifi and another esp32 as bluetooth sender

**Comment by WerkAG** [comment]
Why complicate? Edzelf suggestion its easy to implement, doesn't require any software changes and works great.
