### ISSUE TITLE
Is vs1003 supported? Because I have no sound.

### ISSUE THREAD

**Issue by patryk84a** [Edzelf/ESP32Radio-V2#96]
I defined vs1003 instead of vs1053, still no sound. Are xcs, xdcs and dreq pins connected for vs1003? Does ISP need to be plugged in too? It misses the general connection diagram.

**Comment by Roysen66** [comment]
@patryk84a Did you find any solution to your problem? I'm not able to get any sound out of my VS1003 (VS1003 is defined here too). My board is marked as VS1003/VS1053. Difficult to find 1053 online.
